import React, { useState, useEffect } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { getMfaSetupApi, confirmMfaApi } from "../api/auth";
import toast from "react-hot-toast";

const SetupMFA = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [qrCode, setQrCode] = useState("");
  const [secret, setSecret] = useState("");
  const [code, setCode] = useState("");
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);

  // Grab tempToken passed from login redirection
  const tempToken = location.state?.tempToken;

  useEffect(() => {
    // If tempToken is present, configure it globally for this setup session
    if (tempToken) {
      localStorage.setItem("accessToken", tempToken);
    }

    const fetchMfaSetup = async () => {
      try {
        const data = await getMfaSetupApi();
        setQrCode(data.qr_code_base64);
        setSecret(data.secret);
      } catch (err) {
        toast.error("Failed to generate MFA setup keys");
        navigate("/login");
      } finally {
        setLoading(false);
      }
    };

    fetchMfaSetup();
  }, [tempToken, navigate]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (code.length !== 6) {
      toast.error("Please enter a valid 6-digit code");
      return;
    }

    setSubmitting(true);
    try {
      await confirmMfaApi(code);
      toast.success("Multi-Factor Authentication enabled successfully");
      
      // Remove tempToken so that next API calls pull from normal flow or re-login
      localStorage.removeItem("accessToken");
      navigate("/login");
    } catch (err) {
      toast.error(err.response?.data?.detail || "Invalid code. Please try again.");
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div class="min-h-screen flex items-center justify-center bg-slate-50">
        <div class="animate-spin rounded-full h-10 w-10 border-b-2 border-brand-800"></div>
      </div>
    );
  }

  return (
    <div class="min-h-screen bg-slate-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
      <div class="sm:mx-auto sm:w-full sm:max-w-md">
        <h1 class="text-center text-3xl font-extrabold text-brand-800 tracking-tight">Enable MFA Security</h1>
        <p class="mt-2 text-center text-sm text-slate-500 font-medium">
          Secure your account using Google Authenticator or any TOTP provider.
        </p>
      </div>

      <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
        <div class="bg-white py-8 px-4 shadow-sm sm:rounded-lg sm:px-10 border border-slate-200 space-y-6">
          <div class="text-sm text-slate-600">
            <span class="font-bold text-slate-800">Step 1:</span> Scan the QR code below using your authenticator application.
          </div>

          <div class="flex flex-col items-center justify-center p-4 bg-slate-50 border border-slate-200 rounded-lg">
            {qrCode ? (
              <img
                src={`data:image/png;base64,${qrCode}`}
                alt="Authenticator QR Code"
                class="w-48 h-48"
              />
            ) : (
              <div class="w-48 h-48 flex items-center justify-center border border-slate-300 rounded text-slate-400 text-xs">
                QR Code Error
              </div>
            )}
            <div class="mt-4 text-center">
              <p class="text-xs text-slate-500">Or manually type this secret key:</p>
              <p class="text-sm font-mono font-bold text-brand-800 tracking-widest mt-1 bg-white px-3 py-1.5 border rounded">
                {secret}
              </p>
            </div>
          </div>

          <div class="text-sm text-slate-600">
            <span class="font-bold text-slate-800">Step 2:</span> Enter the 6-digit confirmation code generated by your app.
          </div>

          <form onSubmit={handleSubmit} class="space-y-4">
            <div>
              <input
                type="text"
                maxLength="6"
                pattern="\d{6}"
                placeholder="000000"
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
                class="block w-full px-3 py-2 border border-slate-300 rounded-md shadow-sm text-center text-xl font-bold tracking-widest focus:outline-none focus:ring-brand-800 focus:border-brand-800 bg-slate-50"
              />
            </div>

            <button
              type="submit"
              disabled={submitting || code.length !== 6}
              class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-brand-800 hover:bg-brand-700 focus:outline-none disabled:bg-slate-300 transition-colors"
            >
              {submitting ? "Verifying..." : "Confirm & Setup"}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default SetupMFA;
